name: Performance Test


on:
  workflow_dispatch:

  push:
    branches: 
      [ master, develop, release ]

  pull_request:
    branches: 
      [ master, develop, release ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Test with pytest
      run: |
        pytest ./test/performancetest

    - name: Create artifact
      uses: actions/upload-artifact@v2
      with:
        name: data-parser-session
        path: test/performancetest/results/*
      if: ${{ always() }}