name: Create tag and release (Release)


on:
  push:
    branches:
      - release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'

    - name: Get previous tag
      id: tag_version
      uses: "WyriHaximus/github-action-get-previous-tag@v1"

    - name: Create a GitHub release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.tag_version.outputs.tag }}
        release_name: Release ${{ steps.tag_version.outputs.tag }}
        body: ${{ steps.tag_version.outputs.changelog }}

    - name: Create artifact
      uses: actions/upload-artifact@v2
      with:
        name: release-${{ steps.tag_version.outputs.tag }}
        path: ./* 
      if: ${{ always() }}